apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaria-app
  labels:
    app: myaria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myaria
  template:
    metadata:
      labels:
        app: myaria
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: myaria-container
        image: docker.io/karl123/myaria-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # <-- MODIFICATION : Le conteneur écoute sur 8080 en interne
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: myaria-service
spec:
  type: NodePort # <-- MODIFICATION : On passe en NodePort pour que le DAST puisse y accéder depuis la VM
  selector:
    app: myaria
  ports:
  - port: 80       # Le port du service reste 80
    targetPort: 8080 # <-- MODIFICATION : Il redirige le trafic vers le 8080 du conteneur
    nodePort: 30080  # <-- MODIFICATION : Bloque le port 30080 sur ta VM pour le scan DAST