server {
    listen 8080;
    server_name localhost;

    # DURCISSEMENT DEVSECOPS : Ajout des en-têtes de sécurité HTTP manquants
    add_header X-Frame-Options "SAMEORIGIN" always;                                 # Règle le WARN: Missing Anti-clickjacking
    add_header X-Content-Type-Options "nosniff" always;                             # Règle le WARN: X-Content-Type-Options Missing
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';" always; # Règle le WARN: CSP Not Set
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always; # Règle le WARN: Permissions Policy Not Set
    add_header Cross-Origin-Embedder-Policy "require-corp" always;                 # Règle le WARN: COEP Missing

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}