name: DevSecOps Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  security-audit:
    name: Run Security Scans & DAST
    runs-on: self-hosted # Exécuté localement sur ta VM SR1

    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Scan des Secrets (TruffleHog)
      - name: TruffleHog OSS Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --only-verified

      # Étape 3 : Scan des Dépendances (Trivy fs)
      - name: Run Trivy FS scanner (packages)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # ==========================================
      # SÉCURITÉ DOCKER (CONSTRUCTION & DOUBLE SCAN)
      # ==========================================

     # Étape 4 : Construire l'image Docker avec le tag Docker Hub
      - name: Build Docker Image
        run: |
          # On tague l'image avec ton nom d'utilisateur Docker Hub
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myaria-app:latest .

      # Étape 5 : Premier Scan de l'image (Trivy Image)
      - name: Run Trivy Image scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/myaria-app:latest'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # Connexion obligatoire à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 5.5 : Pousser l'image sécurisée sur Docker Hub
      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myaria-app:latest

      # Étape 6 : Deuxième Scan de l'image (Docker Scout)
      - name: Run Docker Scout cves scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ secrets.DOCKERHUB_USERNAME }}/myaria-app:latest
          exit-code: true
          only-severities: critical,high

      # Étape 7 : Scan SAST (Semgrep)
      - name: Run Semgrep OSS
        uses: semgrep/semgrep-action@v1
        with:
          config: p/security-audit

     # Étape 10 : Appliquer le manifeste mis à jour sur K3s
      - name: Deploy to K3s cluster
        run: |
          kubectl apply -f deployment.yml
          kubectl rollout status deployment/myaria-app --timeout=90s

      # Étape 11 : Lancement du Scan DAST (OWASP ZAP Baseline)
      - name: Run OWASP ZAP DAST Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          # On attaque l'application via le port NodePort exposé sur la boucle locale de ta VM
          target: 'http://127.0.0.1:30080'
          fail_action: false # Mets "true" si tu veux bloquer le pipeline en cas de vulnérabilité web trouvée