name: DevSecOps Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  security-audit:
    name: Run Security Scans
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      # Étape 1 : Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Étape 2 : Scan des Secrets (TruffleHog)
      - name: TruffleHog OSS Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --only-verified

      # Étape 3 : Scan des Dépendances (Trivy fs)
      - name: Run Trivy FS scanner (packages)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # ==========================================
      # SÉCURITÉ DOCKER (CONSTRUCTION & DOUBLE SCAN)
      # ==========================================

      # Étape 4 : Construire l'image Docker localement
      - name: Build Docker Image
        run: |
          docker build -t mon-app:test .

      # Étape 5 : Premier Scan de l'image (Trivy Image)
      - name: Run Trivy Image scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'mon-app:test'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # Connexion obligatoire à Docker Hub pour que Docker Scout fonctionne
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 6 : Deuxième Scan de l'image (Docker Scout)
      # Analyse croisée pour n'avoir aucun angle mort
      - name: Run Docker Scout cves scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: mon-app:test
          exit-code: true # Fait échouer le pipeline si Docker Scout trouve des failles selon vos politiques de sécurité
          only-severities: critical,high # On se concentre uniquement sur le plus dangereux

  # Étape 7 : Scan SAST de votre propre code source (Semgrep)
      - name: Run Semgrep OSS
        uses: semgrep/semgrep-action@v1
        with:
          config: p/security-audit # Utilise le pack de règles de sécurité standards
          exit-code: true # Fait échouer le pipeline si une faille de code est détectée

# Étape 9 : Configuration de la clé SSH native (Méthode Linux robuste)
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          # On écrit le secret GitHub directement dans le fichier de clé de l'agent
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          # Sécurisation stricte des droits exigée par OpenSSH
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519


 # Étape 10 : Exécuter le scan Checkov (IaC) pour valider l'Ansible
      - name: Run Checkov IaC Scanner
        uses: bridgecrewio/checkov-action@master
        with:
          framework: ansible
          output_format: cli
          soft_fail: false
